name: biscuit
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - torchvision
  - cudatoolkit=11.3
  - torchaudio
  - scipy
  - matplotlib
  - seaborn
  - tensorboard
  - networkx
  - pydot
  - numpy
  - pytorch
  - pytorch-cuda=11.7
  - pip
  - pip:
    - ai2thor
    - causal_world
    - pybullet
    - pytorch-lightning
    - imageio
    - optuna


from ai2thor.controller import Controller
from ai2thor.platform import CloudRendering

controller = Controller(
    platform=CloudRendering,
    agentMode="default",
    visibilityDistance=1.5,
    scene="FloorPlan212",

    # step sizes
    gridSize=0.25,
    snapToGrid=True,
    rotateStepDegrees=90,

    # image modalities
    renderDepthImage=False,
    renderInstanceSegmentation=False,

    # camera properties
    width=300,
    height=300,
    fieldOfView=90
)